[project]
name = "day2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tushar Mitra", email = "mitratushar2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "groq>=1.7.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
day2 = "day2:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
